In [1]:
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6]])
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

<class 'numpy.ndarray'>
2
(2, 3)
6
int32


In [2]:
a=np.array([[1,2,3],[4,5,6]],dtype=float)
b=np.array((1,3,2))
c=np.zeros((3,4))
d=np.full((3,3),6,dtype='complex')
e=np.random.random((2,2))
f=np.arange(0,30,5)
g=np.linspace(0,5,10)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

[[1. 2. 3.]
 [4. 5. 6.]]
[1 3 2]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
[[0.33627636 0.40911159]
 [0.2864611  0.62759429]]
[ 0  5 10 15 20 25]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [3]:
arr=np.array([[1,2,3,4],
              [5,2,4,2],
              [1,2,0,1]])
newarr=arr.reshape(2,2,3)
print(arr)
flarr=arr.flatten()
print(flarr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[1 2 3 4 5 2 4 2 1 2 0 1]


In [4]:
arr=np.array([[-1,2,0,4],
              [4,-0.5,6,0],
              [2.6,0,7,8],
              [3,-7,4,2]])
temp=arr[:2,::2]
print(temp)
temp=arr[[0,1,2,3],[3,2,1,0]]
print(temp)
cond=arr>0
temp=arr[cond]
print(temp)

[[-1.  0.]
 [ 4.  6.]]
[4. 6. 0. 3.]
[2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [5]:
a=np.array([1,2,5,3])
print(a+1)
print(a-3)
print(a+10)
print(a**2)
a*=2
print(a)
a=np.array([[1,2,3],[3,4,5],[9,6,0]])
print(a)
print(a.T)

[2 3 6 4]
[-2 -1  2  0]
[11 12 15 13]
[ 1  4 25  9]
[ 2  4 10  6]
[[1 2 3]
 [3 4 5]
 [9 6 0]]
[[1 3 9]
 [2 4 6]
 [3 5 0]]


In [6]:
arr=np.array([[1,5,6],
              [4,7,2],
              [3,1,9]])
print(arr.max())
print(arr.max(axis=1))
print(arr.min(axis=0))
print(arr.sum())
print(arr.cumsum(axis=1))

9
[6 7 9]
[1 1 2]
38
[[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [7]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[4,3],
            [2,1]])
print(a+b)
print(a*b)
print(a.dot(b))

[[5 5]
 [5 5]]
[[4 6]
 [6 4]]
[[ 8  5]
 [20 13]]


In [8]:
a=np.array([0,np.pi/2,np.pi])
print(np.sin(a))
a=np.array([0,1,2,3])
print(np.exp(a))
print(np.sqrt(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]


In [9]:
a=np.array([[1,4,2],
            [3,4,6],
            [0,-1,5]])
print(np.sort(a,axis=None))
print(np.sort(a,axis=1))
print(np.sort(a,axis=0,kind='mergesort'))
dtypes=[('name','S10'),('grad_year',int),('cgpa',float)]
values=[('Hrithik',2009,8.5),('Ajay',2008,8.7),('Pankaj',2008,7.9)]
arr=np.array(values,dtype=dtypes)
print(np.sort(arr,order='name'))

[-1  0  1  2  3  4  4  5  6]
[[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
[[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]
[(b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5) (b'Pankaj', 2008, 7.9)]


In [10]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
print(np.vstack((a,b)))
print(np.hstack((a,b)))
c=[5,6]
print(np.column_stack((a,c)))
print(np.concatenate((a,b),1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5]
 [3 4 6]]
[[1 2 5 6]
 [3 4 7 8]]


In [11]:
a=np.array([[1,3,5,7,9,11],
            [2,4,6,8,10,12]])
print(np.hsplit(a,2))
print(np.vsplit(a,2))

[array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]
[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [13]:
a=np.array(([1,2,3,4],[7,6,2,0]))
print(a)
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [14]:
b=np.array([1,2,3,4,5])
m=sum(b)/5
print(m)
print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [16]:
c=np.array([1,5,4,2,0])
print(np.median(c))
print(np.mean(c))
w=np.ones(5)
print(np.average(c,weights=w))
u=np.mean(c)
myStd=np.sqrt(np.mean(abs(c-u)**2))
print(myStd)
dev=np.std(c)
print(dev)
print(myStd**2)
print(np.var(c))

2.0
2.4
2.4
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


In [17]:
a=np.arange(10)+5
print(a)
np.random.seed(1)
np.random.shuffle(a)
print(a)
a=np.random.randn(2,3)
print(a)
a=np.random.randint(5,10,3)
print(a)
element=np.random.choice([1,4,3,2,11,27])
print(element)

[ 5  6  7  8  9 10 11 12 13 14]
[ 7 14 11  9  5  8  6 12 13 10]
[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]
[7 9 6]
4
