# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

#### 3. Create a null vector of size 10

In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [4]:
a = arr.size
b = arr.itemsize
print("{} bytes".format(a*b))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [5]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\programdata\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the 

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [6]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [7]:
arr=np.linspace(10,49,10)
print(arr)

[10.         14.33333333 18.66666667 23.         27.33333333 31.66666667
 36.         40.33333333 44.66666667 49.        ]


#### 8.  Reverse a vector (first element becomes last)

In [8]:
np.flipud(arr)

array([49.        , 44.66666667, 40.33333333, 36.        , 31.66666667,
       27.33333333, 23.        , 18.66666667, 14.33333333, 10.        ])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
arr = np.random.randint(0,9,(3,3))
arr

array([[6, 7, 3],
       [2, 6, 2],
       [7, 8, 7]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [10]:
arr=[1,2,0,0,4,0]
nzele=[x > 0 for x in arr]
for i in range(len(nzele)):
    if nzele[i]==True:
        print(i)

0
1
4


#### 11. Create a 3x3 identity matrix

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [12]:
np.random.random((3,3,3))

array([[[0.23373594, 0.3462389 , 0.22945192],
        [0.3191471 , 0.46033058, 0.78725356],
        [0.89386694, 0.4166212 , 0.90354597]],

       [[0.80855798, 0.54926457, 0.02720662],
        [0.92354932, 0.8685261 , 0.71831968],
        [0.36659673, 0.42965702, 0.3126543 ]],

       [[0.10445613, 0.86543103, 0.3050178 ],
        [0.31540461, 0.78176278, 0.44043231],
        [0.37457323, 0.2827154 , 0.81351548]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
arr = np.random.random((10,10))
print(arr)
print(np.min(arr))
print(np.max(arr))

[[0.59419619 0.3402287  0.1783834  0.74336063 0.86427602 0.21796037
  0.73299861 0.64427797 0.62699098 0.58002565]
 [0.32583034 0.152239   0.20388962 0.84639665 0.92870198 0.66588502
  0.25675398 0.15953596 0.31792211 0.86509698]
 [0.38618076 0.74073253 0.32781395 0.27544089 0.2799695  0.9813917
  0.89593393 0.53995083 0.2333454  0.84175611]
 [0.59842504 0.81737363 0.14257746 0.71581656 0.79293692 0.5532084
  0.34653478 0.60325934 0.24533495 0.53421681]
 [0.28385825 0.52552121 0.7774423  0.81948637 0.47530391 0.03436781
  0.91470788 0.89243469 0.67485135 0.94945609]
 [0.92038577 0.88884195 0.1455408  0.33583317 0.10464197 0.86455397
  0.14858897 0.826817   0.64508056 0.18361617]
 [0.61407413 0.12047798 0.54975628 0.99639959 0.62218798 0.01769085
  0.35426219 0.93467504 0.13004166 0.50152131]
 [0.36791901 0.48887995 0.0304403  0.82641474 0.49105482 0.89477167
  0.75371989 0.98422325 0.62927118 0.48298015]
 [0.48976676 0.36205222 0.83198952 0.75831449 0.29334589 0.12893773
  0.16189681 0

#### 14. Create a random vector of size 30 and find the mean value

In [14]:
arr = np.random.random((30))
print(arr)
print(np.mean(arr))

[0.30392335 0.34422401 0.76026933 0.25401243 0.72085427 0.25952866
 0.51937164 0.36222687 0.70262934 0.63057632 0.95668993 0.56771534
 0.5605826  0.42037178 0.65831276 0.0141244  0.85166958 0.84806431
 0.43534841 0.64850147 0.90722093 0.89096855 0.77176742 0.76292983
 0.10958135 0.4882795  0.12692011 0.84624556 0.65745793 0.91125403]
0.5763873994436923


#### 15. Create a 2d array with 1 on the border and 0 inside

In [15]:
ans = np.ones((5,5))
ans[1:-1,1:-1] = 0
ans

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [16]:
ans=np.pad(ans,pad_width = 1, mode = 'constant',constant_values = 0)
ans

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
ans = np.diag([1,2,3,4],-1)
ans

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [19]:
ans = np.zeros((8,8),dtype=int)
ans[1::2,::2] = 1
'''
->ans[1::2, ::2]: This is a slice operation that targets specific elements of the array.
->1::2: This selects rows starting from index 1, and then every second row after that (i.e., rows at indices 1, 3, 5, and 7).
->::2: This selects columns starting from index 0, and then every second column after that (i.e., columns at indices 0, 2, 4, and 6).
'''
ans[::2,1::2] = 1
ans

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)